# ==========================================
# ===                GENERAL             ===
# ==========================================
set -g default-terminal "xterm-256color"
set -g history-limit 10000
set -g buffer-limit 20
set -g display-time 1500
set -g remain-on-exit off
set -g repeat-time 300
set -w -g allow-rename off
set -w -g automatic-rename on
set -g mouse on

# Start indexing at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# ==========================================
# ===             KEYBINDINGS            ===
# ==========================================

# Remap prefix to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Quick config reload
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Split panes 
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Switch panes using Alt-arrow
bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Clipboard & Copy Mode -- Wayland specific
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key p run "wl-paste | tmux load-buffer -" \; paste-buffer

# Toggle status bar
bind-key q set-option status

# ==========================================
# ===        STATUS BAR & TITLES         ===
# ==========================================

set-option -g status "on"
set-option -g status-interval 1
set-option -g status-position bottom

# Dynamic Window Renaming - WIP
set-option -g automatic-rename-format '#{?#{m/ri:(bash|zsh|sh),#{pane_current_command}},#{b:pane_current_path},#{pane_current_command}}'

# Colors
set -g status-fg black
set -g status-bg white

# Window status format
set -g window-status-format "#I:#W "
set -g window-status-current-format "[#I:#W]"

# Left/Right Status Content
set -g status-left " #S #{prefix_highlight} "
set -g status-right "%a %Y%m%d %H%M UTC%z "

# Terminal Titles
set -g set-titles on
set -g set-titles-string "tmux - #S :: [#I:#W]"

# ==========================================
# ===               PLUGINS              ===
# ==========================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @prefix_highlight_bg black
set -g @prefix_highlight_fg white
set -g @prefix_highlight_prefix_prompt  ' '
set -g @prefix_highlight_empty_prompt '   '

run '~/.tmux/plugins/tpm/tpm'
